version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=albums
    ports:
      - "5432:5432"
  albums-service:
    image: cleptes/albums:0.01
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/albums
    ports:
      - "8080:8080"
    depends_on:
      - postgres