kumuluzee:
  name: albums-service
  env:
    name: dev
  version: 1.0.0
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
      etcd:
        hosts: http://192.168.99.100:2379
      ttl: 30
      ping-interval: 5

  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/AlbumsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/albums
      username: postgres
      password: postgres
      max-pool-size: 20

songs-endpoint-config:
  is-songs-running: false
