kumuluzee:
  name: albums
  env:
    name: dev
  version: 1.0.0
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
      etcd:
        hosts: http://192.168.99.100:2379
      ttl: 30
      ping-interval: 5

  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/AlbumsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/albums
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
      checks:
        data-source-health-check:
          jndi-name: jdbc/AlbumsDS
  metrics:
          web-instrumentation:
            - name: metricsEndpoint
              url-pattern: /metrics/*
            - name: customersEndpoint
              url-pattern: /v1/albums/*
  logs:
      config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="albums">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <Socket name="logstash" host="27b142a8-85d8-47cc-abe6-2cf9f6d6ed81-ls.logit.io" port="22830"
                                                                                           protocol="tcp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                                <AppenderRef ref="logstash" level="trace"/>
                            </Root>
                        </Loggers>
                    </Configuration>'


