apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: albums-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: albums
    spec:
      containers:
      - image: cleptes/albums
        name: albums
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-albums:5432/albums
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: userdb
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.16.117:31896
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        #resources:
         #limits:
          #cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 3